services:
  - type: worker
    name: ai-course-builder-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -u course_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"

